#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

# what’s keeping your Ubuntu container’s Nginx installation from listening on port 8?
# configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
